# Generated by Django 5.2.11 on 2026-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('cultural', 'Cultural'), ('sports', 'Sports')], default='seminar', max_length=20),
        ),
    ]
