# Generated by Django 5.2.11 on 2026-02-27 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
